# Generated by Django 4.2.3 on 2023-11-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_list', models.TextField(max_length=100, verbose_name='Название основного товара')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Список товаров',
            },
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_sex', models.TextField(max_length=250, verbose_name='Пол')),
                ('title_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksite.list_product')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='women_shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, verbose_name='Название обуви')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото обуви')),
                ('product_type', models.CharField(max_length=250, null=True, verbose_name='Тип обуви')),
                ('slug_group', models.SlugField(max_length=255, null=True, verbose_name='Url товара')),
                ('slug_sex', models.SlugField(max_length=255, null=True, verbose_name='Url пол')),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banksite.list_product', verbose_name='Группа товара')),
                ('sex_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banksite.sex', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Женская обувь',
                'verbose_name_plural': 'Женская обувь',
            },
        ),
        migrations.CreateModel(
            name='men_shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, verbose_name='Название обуви')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото товара')),
                ('product_type', models.CharField(max_length=250, null=True, verbose_name='Тип обуви')),
                ('slug_group', models.SlugField(max_length=255, null=True, verbose_name='Url товара')),
                ('slug_sex', models.SlugField(max_length=255, null=True, verbose_name='Url пол')),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banksite.list_product', verbose_name='Группа товара')),
                ('sex_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banksite.sex', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Мужская обувь',
                'verbose_name_plural': 'Мужская обувь',
            },
        ),
    ]
